### PR TITLE
feat: initial setup

### PR DESCRIPTION
**Pull request by johnnyreilly**
This PR creates our initial package.  I think anyway.   I've created a secret `NPM_TOKEN` - my hope is that when I merge this PR the initial version of `easyauth-deeplink` will be published.

Not used @joshuakgoldberg's template before - but I'm optimistic!

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Ahh love to see this! Please let me know if there's anything that feels off (or just plain doesn't work). I was hoping to get this cleaned up by end of year, but typescript-eslint working has been taking over.

**Comment by johnnyreilly** [comment]
Thanks @JoshuaKGoldberg!  It's really very good!  About to hit merge and see if publishing works.

- Things that I had to figure out for myself: needed to set up an `NPM_TOKEN` variable
- Had to manually delete the `dist` folder

**Comment by johnnyreilly** [comment]
Huh - post publishing the stuff in `dist` has come back @JoshuaKGoldberg  - feels wrong?

**Comment by JoshuaKGoldberg** [comment]
Yeah it's that same bug 😢

**Pull request merged**
